server:
  port: 8090

spring:
  application:
    name: tracecraft-demo-app

logging:
  file:
    name: ${user.dir}/logs/demo-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
